const ActionTypes = {};
[
  "REQUEST_CHRONOS_JOB_CREATE_ERROR",
  "REQUEST_CHRONOS_JOB_CREATE_SUCCESS",
  "REQUEST_CHRONOS_JOB_DELETE_ERROR",
  "REQUEST_CHRONOS_JOB_DELETE_SUCCESS",
  "REQUEST_CHRONOS_JOB_DETAIL_ERROR",
  "REQUEST_CHRONOS_JOB_DETAIL_ONGOING",
  "REQUEST_CHRONOS_JOB_DETAIL_SUCCESS",
  "REQUEST_CHRONOS_JOB_RUN_ERROR",
  "REQUEST_CHRONOS_JOB_RUN_SUCCESS",
  "REQUEST_CHRONOS_JOB_SCHEDULE_UPDATE_ERROR",
  "REQUEST_CHRONOS_JOB_SCHEDULE_UPDATE_SUCCESS",
  "REQUEST_CHRONOS_JOB_STOP_RUN_ERROR",
  "REQUEST_CHRONOS_JOB_STOP_RUN_SUCCESS",
  "REQUEST_CHRONOS_JOB_UPDATE_ERROR",
  "REQUEST_CHRONOS_JOB_UPDATE_SUCCESS",
  "REQUEST_CHRONOS_JOBS_ERROR",
  "REQUEST_CHRONOS_JOBS_ONGOING",
  "REQUEST_CHRONOS_JOBS_SUCCESS"
].forEach(actionType => {
  ActionTypes[actionType] = actionType;
});

module.exports = ActionTypes;
